### ISSUE TITLE
Aggiungere template file  .h con struttura quadrilatero

### ISSUE THREAD

**Issue by StefanoPeroceschi** [StefanoPeroceschi/MartinettoQuadrilatero#1]
@DavidLeoni  Può andare bene il componente scelto con i 3 parametri specificati in figura?

**Comment by DavidLeoni** [comment]
Mi sembra un po' semplice, nel senso, al di là di fare un check che il raggio delle giunzioni non sia eccessivo e in genere non si abbiano valori negativi, che altri controlli faresti?

**Comment by StefanoPeroceschi** [comment]
Tipo per esempio che l'altezza totale sia minore di 2*lunghezza aste, potrei mettere inoltre una altezza minima in modo che le aste non si sovrappongano.
Sarebbe comunque possibile sviluppare il componente con magari più parametri per aumentare il numero di controlli? 
Come per esempio rendere indipendente in raggio dei perni dallo spessore delle aste per fare si che ci sia un'ulteriore check in quanto lo spessore deve essere maggiore del raggio del perno?

**Comment by DavidLeoni** [comment]
sì ecco basta che ci sia un po' di sostanza
