### ISSUE TITLE
Integrazione guida prismatica per eseguire alzata meccanismo a forbice

### ISSUE THREAD

**Issue by StefanoPeroceschi** [StefanoPeroceschi/MartinettoQuadrilatero#18]
Integrare quida prismatica nell'oggetto scrissor lift per eseguire l'azionamento di alzata del componente
codice di guida prismatica di @matteodv99tn

**Comment by matteodv99tn** [comment]
Ciao!

Grazie, ho visto che ti va di integrare il mio device! Se avessi problemi nell'implementazione fammi sapere, se ti servissero alcune funzionalità particolari resto a disposizione per programmare tutto. Sto finendo di implementare ora la rappresentazione delle dimensioni dei componenti.

**Comment by StefanoPeroceschi** [comment]
@matteodv99tn

Ciao,

Grazie a te, devo ancora integrare il tuo codice comunque grazie della disponibilità
a breve proverò a fare una pull request

**Comment by StefanoPeroceschi** [comment]
Il commit  cf5dfc6bb3dc5aa46b72b518a9b6de2fcbd8d289 si riferisce all'integrazione dei file di matteodv99tn presi dalla versione v1.2.0 in particolare dal commit aaa419e6dad65d1e1f0a030265be19adead51817 dalla repository [TPA-homework1](https://github.com/matteodv99tn/TPA-homework1)
